target 'iosApp' do
  use_frameworks!
  platform :ios, '15.1'
  pod 'SwiftLint'
  pod 'AlertToast'
  pod 'Firebase/AnalyticsWithoutAdIdSupport'
  pod 'FirebaseMessaging'
  pod 'shared', :path => '../shared'
end
